<!-- <?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://com/prova/e_commerce/dbRel/oracle/jpa/soap"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap"
                  name="UsersService"
                  targetNamespace="http://com/prova/e_commerce/dbRel/oracle/jpa/soap">

     Definizione dei tipi (schema) 
    <wsdl:types>
        <xsd:schema targetNamespace="http://com/prova/e_commerce/dbRel/oracle/jpa/soap">
        
         <xsd:import namespace="http://com/prova/e_commerce/dbRel/oracle/jpa/soap" schemaLocation="wsdl/schema/UserServiceSchema.xsd"/>
  
             Definizione di un singolo utente 
            <xsd:complexType name="User">
                <xsd:sequence>
                    <xsd:element name="id" type="xsd:string"/>
                    <xsd:element name="firstName" type="xsd:string"/>
                    <xsd:element name="lastName" type="xsd:string"/>
                    <xsd:element name="username" type="xsd:string"/>
                    <xsd:element name="email" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>

             Definizione delle risposte per operazioni che restituiscono utenti 
            <xsd:complexType name="UsersListResponse">
                <xsd:sequence>
                    <xsd:element name="user" maxOccurs="unbounded" type="tns:User"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="UserResponse">
                <xsd:sequence>
                    <xsd:element name="user" type="tns:User"/>
                </xsd:sequence>
            </xsd:complexType>

             Definizioni di richiesta per operazioni 
            <xsd:complexType name="GetUserByIdRequest">
                <xsd:sequence>
                    <xsd:element name="id" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="GetUserByUsernameRequest">
                <xsd:sequence>
                    <xsd:element name="username" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="GetUserByEmailRequest">
                <xsd:sequence>
                    <xsd:element name="email" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="AddUserRequest">
                <xsd:sequence>
                    <xsd:element name="user" type="tns:User"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="UpdateUserRequest">
                <xsd:sequence>
                    <xsd:element name="user" type="tns:User"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="DeleteUserRequest">
                <xsd:sequence>
                    <xsd:element name="id" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </wsdl:types>

     Definizione dei messaggi 
    <wsdl:message name="GetUserByIdRequest">
        <wsdl:part name="parameters" element="tns:GetUserByIdRequest"/>
    </wsdl:message>

    <wsdl:message name="GetUserByIdResponse">
        <wsdl:part name="parameters" element="tns:UserResponse"/>
    </wsdl:message>

    <wsdl:message name="GetUserByUsernameRequest">
        <wsdl:part name="parameters" element="tns:GetUserByUsernameRequest"/>
    </wsdl:message>

    <wsdl:message name="GetUserByUsernameResponse">
        <wsdl:part name="parameters" element="tns:UserResponse"/>
    </wsdl:message>

    <wsdl:message name="GetUserByEmailRequest">
        <wsdl:part name="parameters" element="tns:GetUserByEmailRequest"/>
    </wsdl:message>

    <wsdl:message name="GetUserByEmailResponse">
        <wsdl:part name="parameters" element="tns:UserResponse"/>
    </wsdl:message>

    <wsdl:message name="GetAllUsersRequest">
        <wsdl:part name="parameters" element="tns:UsersListResponse"/>
    </wsdl:message>

    <wsdl:message name="AddUserRequest">
        <wsdl:part name="parameters" element="tns:AddUserRequest"/>
    </wsdl:message>

    <wsdl:message name="AddUserResponse">
        <wsdl:part name="parameters" element="tns:UserResponse"/>
    </wsdl:message>

    <wsdl:message name="UpdateUserRequest">
        <wsdl:part name="parameters" element="tns:UpdateUserRequest"/>
    </wsdl:message>

    <wsdl:message name="UpdateUserResponse">
        <wsdl:part name="parameters" element="tns:UserResponse"/>
    </wsdl:message>

    <wsdl:message name="DeleteUserRequest">
        <wsdl:part name="parameters" element="tns:DeleteUserRequest"/>
    </wsdl:message>

    <wsdl:message name="DeleteUserResponse">
        <wsdl:part name="parameters" element="tns:UserResponse"/>
    </wsdl:message>

     Definizione del portType 
    <wsdl:portType name="UsersPortType">
        <wsdl:operation name="getUserById">
            <wsdl:input message="tns:GetUserByIdRequest"/>
            <wsdl:output message="tns:GetUserByIdResponse"/>
        </wsdl:operation>

        <wsdl:operation name="getUserByUsername">
            <wsdl:input message="tns:GetUserByUsernameRequest"/>
            <wsdl:output message="tns:GetUserByUsernameResponse"/>
        </wsdl:operation>

        <wsdl:operation name="getUserByEmail">
            <wsdl:input message="tns:GetUserByEmailRequest"/>
            <wsdl:output message="tns:GetUserByEmailResponse"/>
        </wsdl:operation>

        <wsdl:operation name="getAllUsers">
            <wsdl:input message="tns:GetAllUsersRequest"/>
            <wsdl:output message="tns:GetAllUsersResponse"/>
        </wsdl:operation>

        <wsdl:operation name="addUser">
            <wsdl:input message="tns:AddUserRequest"/>
            <wsdl:output message="tns:AddUserResponse"/>
        </wsdl:operation>

        <wsdl:operation name="updateUser">
            <wsdl:input message="tns:UpdateUserRequest"/>
            <wsdl:output message="tns:UpdateUserResponse"/>
        </wsdl:operation>

        <wsdl:operation name="deleteUserById">
            <wsdl:input message="tns:DeleteUserRequest"/>
            <wsdl:output message="tns:DeleteUserResponse"/>
        </wsdl:operation>
    </wsdl:portType>

     Definizione del binding 
    <wsdl:binding name="UsersBinding" type="tns:UsersPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="getUserById">
            <soap:operation soapAction="getUserById"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="getUserByUsername">
            <soap:operation soapAction="getUserByUsername"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="getUserByEmail">
            <soap:operation soapAction="getUserByEmail"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="getAllUsers">
            <soap:operation soapAction="getAllUsers"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="addUser">
            <soap:operation soapAction="addUser"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="updateUser">
            <soap:operation soapAction="updateUser"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="deleteUserById">
            <soap:operation soapAction="deleteUserById"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

     Definizione del servizio 
    <wsdl:service name="UsersService">
        <wsdl:port name="UsersPort" binding="tns:UsersBinding">
            <soap:address location="http://localhost:8080/soap/users"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
 -->